
model_list:
  - model_name: ollama
    litellm_params:
      model: ollama/llama3.1
      api_base: http://localhost:11434
      api_key: sk-no-key-needed
      api_type: openai
      llm_provider: ollama

litellm_settings:
  drop_params: true
  set_verbose: true

